# Auto-generated by bot-deploy MCP
FROM node:20-alpine
WORKDIR /app

# Install dependencies first for efficient layer caching
COPY package*.json ./
RUN npm install --production

# Copy application source
COPY . .

# Expose web / health check port
EXPOSE 3000

# Start command
CMD ["npm", "start"]
